### ISSUE TITLE
[Bug]: Identification options missing in Shiny app

### ISSUE THREAD

**Issue by GCov** [wincowgerDEV/OpenSpecy-package#179]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Platform and OS Version

shiny app

### Existing Issues

no

### What happened?

The identification options seem to be missing from the identification tab. Currently, the only available option is: 'AI: Both Deriv Mediod'

### Steps to reproduce

1.Go to https://www.openanalysis.org/openspecy/
2.Expand Identification tab

### Expected behavior

Their should have been additional matching options. Likely something got changed in a recent post that dropped these options.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/84ab9a7c-3a79-4927-840a-b2dc59c94d51)

**Comment by wincowgerDEV** [comment]
Hey @GCov , thanks for letting us know about this! We are working to try and get all the libraries added, for now running the app through the r package using run_app is the best option as it will give you everything.

**Comment by wincowgerDEV** [comment]
@GCov, new libraries are online now! We can't add the full library any more due to its size with the new interface but we have two different medoid options now (these have 4k spectra each and they are just the full library without redundant spectra). We also added a model based identification so you have a total of 4 options to id with :)
