### ISSUE TITLE
Define own class for spectral data to reduce error handling/checking?

### ISSUE THREAD

**Issue by zsteinmetz** [wincowgerDEV/OpenSpecy-package#5]
This is more a reminder to myself but we can also discuss it here :smile: 

In the long run, we could think about creating an own class for spectral data that follows a defined structure. This class can then be the preferred input for all functions/methods. This will make it easier to check for user errors on the one hand. One the other hand, this gives less control to the user.

I did that with my other [package](https://github.com/zsteinmetz/envalysis/blob/main/R/calibration.R) where I defined a new class `calibration` that takes calibration data in a defined way. LODs and LOQ are then calculated only from those class objects.

**Comment by wincowgerDEV** [comment]
@zsteinmetz should we close this now since we have the data format we like for the library or should it stay open? I think we may need to revisit this for the newer larger datasets since I think they are actually going to need to be split up as individual files and read in one at a time to make it work.
